### ISSUE TITLE
Problems running TensorKart (./record.py) with MuPen64Plus!

### ISSUE THREAD

**Issue by shyamalschandra** [kevinhughes27/TensorKart#11]
Hi!

After installing all the requirements and dependencies, I ran the following command along with an instance of MuPen64Plus running Mario Kart 64.

Input:

`./record.py`

This is what happened...

Output:
```
iMac:TensorKart shyamalsuhanachandra$ ./record.py
2017-01-19 19:37:50.129 Python[14589:68221] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/m1/b_t9_2151y30ryvtr_2gznch0000gp/T/org.python.python.savedState
Traceback (most recent call last):
  File "./record.py", line 207, in <module>
    app.frame = MainWindow()
  File "./record.py", line 30, in __init__
    self.create_main_panel()
  File "./record.py", line 49, in create_main_panel
    img = wx.Image(320,240)
  File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 2882, in __init__
    _core_.Image_swiginit(self,_core_.new_Image(*args, **kwargs))
TypeError: String or Unicode type required
```

How can I fix this problem?  

Note: I didn't make any changes to the code besides install the dependencies with brew instead of pip in certain scenarios.  Also, the screen in MuPen64Plus flickers quite a bit, what should I do to prevent this from happening?

**Comment by kevinhughes27** [comment]
Looks like an issue with `wx-python` I'd love to remove the dependency on this library but that requires re-writing the record.py GUI. I would check the wx forums, help etc to try and fix this. Same for the Mupen64plus flicker - they have their own issue tracker. 

If you find a fix please post back here! Or if you're up for removing wx then I'll happily accept the PR!

**Comment by crypdick** [comment]
@kevinhughes27 This is a show-stopper for me, too. I don't have any experience with python guis, what libraries should I look at?

**Comment by kevinhughes27** [comment]
Can you post some information about your system? OS and wx version. To keep things simple maybe try and get a simple wx hello world app running and then try TensorKart

**Comment by crypdick** [comment]
I am running Linux Mint 18 64-bit, wx.version() is '3.0.2.0 gtk2 (classic)'. [This hello world](https://wiki.wxpython.org/Getting%20Started#A_First_Application:_.22Hello.2C_World.22) app runs fine, but running `record.py` gives:

```python
/usr/bin/python2.7 /home/pepe/Apps/TensorKart/record.py
Traceback (most recent call last):
  File "/home/pepe/Apps/TensorKart/record.py", line 218, in <module>
    app.frame = MainWindow()
  File "/home/pepe/Apps/TensorKart/record.py", line 31, in __init__
    self.create_main_panel()
  File "/home/pepe/Apps/TensorKart/record.py", line 51, in create_main_panel
    img = wx.Image(320, 240)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 2882, in __init__
    _core_.Image_swiginit(self,_core_.new_Image(*args, **kwargs))
TypeError: String or Unicode type required
```

**Comment by kevinhughes27** [comment]
the image api has changed around a few times. It used to be wx.Bitmap. I would look around at the docs and see what you find. I am using 3.0.3 on Linux mint so you could also just try to up the version.

**Comment by simama** [comment]
Hi. I managed to solve the problem in this way. 
```python
# Images
img = wx.EmptyImage(320,240)
self.image_widget = wx.StaticBitmap(self.img_panel, wx.ID_ANY, wx.EmptyBitmap(320,240))
```
```python
def take_screenshot(self):
    screen = wx.ScreenDC()
    bmp = wx.EmptyBitmap(Screenshot.SRC_W, Screenshot.SRC_H)
    mem = wx.MemoryDC(bmp)
    mem.Blit(0, 0, Screenshot.SRC_W, Screenshot.SRC_H, screen, Screenshot.OFFSET_X, 
    Screenshot.OFFSET_Y)
    return bmp
```
