### ISSUE TITLE
Choppy sound issue

### ISSUE THREAD

**Issue by snawara** [kevinhughes27/TensorKart#14]
I have to mute the audio while watching the network play because it becomes very choppy/laggy. The audio is fine when I am recording though. Does anyone else have this problem? 

Btw, I think a nice improvement would be to include audio snapshots as input to the network.

**Comment by kevinhughes27** [comment]
What are your system specs? Running both the AI and the emulator probably takes a fair amount of computing resources. I didn't have this issue on my system though.

**Comment by snawara** [comment]
Rampage IV Extreme (onboard audio)
Core i7 3820 
GeForce GTX 750 Ti

I was running mint off a flash drive (usb 3.0) though, so that may be it.

**Comment by kevinhughes27** [comment]
Okay - I'm not really sure if this is a TensorKart issue or what we can do it about it.
