### ISSUE TITLE
Black screen capture on mac

### ISSUE THREAD

**Issue by AC3LAB5** [kevinhughes27/TensorKart#15]
Crudely changed take screenshot in utils.py as per http://wxpython-users.1045709.n5.nabble.com/ScreenDC-wxMac-td2358205.html:

import os
def take_screenshot():
    os.system('screencapture scr.png') 
    screen = wx.Bitmap('scr.png')
    return screen.GetSubBitmap(wx.Rect(10,60,615,480))

edit: removed unused lines. Also not quite sure how yet, but need to remove alpha from screenshot. e.g. to remove in prepare samples: imread(image_file)[:,:,:3] however, this leaves the play.py with an alpha layer since it uses take_screenshot() as well

**Comment by kevinhughes27** [comment]
cc @mBeierl - you were looking at cross-platform screenshots so this might interest you.

**Comment by mBeierl** [comment]
I'm working on the PyQt port in my fork right now. Will be finished in a few days and I'll create a PR with the finished port.

**Comment by kevinhughes27** [comment]
closing in favour of #53
