### ISSUE TITLE
Image size question

### ISSUE THREAD

**Issue by bzier** [kevinhughes27/TensorKart#18]
@kevinhughes27 Just curious about the sizes used in utils.py. On my machine, the default mupen64plus window is 640x480, yet you're using a rectangle of 615x480. Also, in prepare_image() you are resizing the image to 200x66. Can you help me understand why these sizes are being used in this way? Also, why the call to reshape the image array prior to resizing it? Thanks.

**Comment by bzier** [comment]
I spent some time on this yesterday and I understand the reshape call now. I am guessing that the resize is to reduce the amount of data to be processed, but I'd like to understand if that is really the case. Still curious about the chosen sizes though.

**Comment by kevinhughes27** [comment]
The first size is what the emulator opens up as on my machine. The second size was dictated by the nvidia model. I opted to use their sizes rather than recalculate all the layer sizes. The size of the image is somewhat arbitrary and doesn't have an obvious affect on the network.
