### ISSUE TITLE
Multi level

### ISSUE THREAD

**Issue by diegoalejogm** [kevinhughes27/TensorKart#20]
Does this approach extrapolate to different levels? If I train my net with level A, would the trained model work with level B?

**Comment by millerda** [comment]
In my experience it does work somewhat (I have only recorded data for a few levels). I trained on a few different levels and then tried playing a previously unseen level with the trained model. The AI was not able to complete the level without any help, but it did do fine for stretches of time (even sliding appropriately at times). The model is able to more or less complete one of the levels I trained it on by itself (though this isn't really that impressive, it is still cool to see it happen, even finishing in 1st place for a 50cc race).

With more data, it is possible that a model would generalize well for unseen levels, but how much more data is anyone's guess. There are probably other techniques that could be used to speed up learning as well, but I am not an expert by any means. Currently I am hampered by having to use an old laptop with a Core 2 duo cpu and only 2gb of RAM (almost 3 hours to train on ~800mb of data, can't get this project running on my Mac for the life of me).

**Comment by diegoalejogm** [comment]
Have you tried to teach it to play using reinforcement learning?

**Comment by kevinhughes27** [comment]
TensorKart doesn't use reinforcement learning (yet). I think this would be a really cool project for someone to pick up! I'd happily donate a server to let it play and learn forever if someone does this.

**Comment by kevinhughes27** [comment]
I am going to close this issue as there isn't anything specifically actionable here. 

Maybe we need a place to have discussions like this? Sounds like a few people are experimenting with TensorKart. I don't have any concrete suggestions on what but if someone sets something up I'll join.
