### ISSUE TITLE
ctrl-c doesn't stop play.py

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/TensorKart#23]
I always have to use `ctrl z` to put it in the background and use `kill -9 _pid_`. I am wondering if this is related to the code or my system (I was messing with a bunch of things when I wrote this to try and dpo fake joysticks).

@bzier @snawara does this happen to either of you?

**Comment by bzier** [comment]
Yeah, I have been using `ctrl \` which kills python in a less-than-graceful way. I haven't taken the time to figure it out yet either. Will submit a PR if I do.

**Comment by bzier** [comment]
Oops I forgot, I actually did look into this. I think it is because of the HTTPServer.server_forever()` call. I put it on a background thread and then just did a `raw_input()` call to wait for `ENTER` to be pressed. That worked reasonably well.
