### ISSUE TITLE
Screenshots with gtk?

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/TensorKart#33]
Someone posted this link on HN https://www.pastery.net/xafjmn/ (from this article https://news.ycombinator.com/item?id=14145551)

Its a GTK screen cap that might work better.

**Comment by crypdick** [comment]
pastery link is broken

**Comment by kevinhughes27** [comment]
works for me!

```python
from gtk import gdk
from PIL import Image


class Capturer(object):
    "A class that will take a screenshot of a single pixel on a GTK system."
    def __init__(self, w=None, h=None):
        self._w = w if w else gdk.screen_width()
        self._h = h if h else gdk.screen_height()

        self._window = gdk.get_default_root_window()
        self._pb = gdk.Pixbuf(gdk.COLORSPACE_RGB, False, 8, self._w, self._h)

    def screenshot(self, x, y):
        pb = self._pb.get_from_drawable(self._window, self._window.get_colormap(), x, y, 0, 0, self._w, self._h)
        image = Image.frombuffer('RGB', (self._w, self._h), pb.get_pixels(), 'raw', 'RGB', pb.get_rowstride(), 1)
        return image
```

**Comment by crypdick** [comment]
@kevinhughes27 I emailed Stavros Korokithakis (the author of that comment) last night and he reposted it ^_^

**Comment by kevinhughes27** [comment]
Ahh thanks!!

On Jun 1, 2017 9:50 PM, "Richard Decal" <notifications@github.com> wrote:

@kevinhughes27 <https://github.com/kevinhughes27> I emailed Stavros
Korokithakis (the author of that comment) last night and he reposted it ^_^

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kevinhughes27/TensorKart/issues/33#issuecomment-305499106>,
or mute the thread

**Comment by kevinhughes27** [comment]
closing in favour of #53
