### ISSUE TITLE
Errors with new gym-based play.py

### ISSUE THREAD

**Issue by millerda** [kevinhughes27/TensorKart#34]
When I try to use play.py to see how my trained model performs, I get errors. Due to that final OSError, I thought it might need to be ran as root, but that didn't help either. Does this fit more as an issue with gym-mupen64plus @bzier ?

```
[2017-04-24 17:47:35,617] Making new env: Mario-Kart-Luigi-Raceway-v0
('ControllerHTTPServer started on port ', 8082)
initial_disp: :0
Starting xvfb with command: ['Xvfb', ':1', '-screen', '0', '640x480x24', '-fbdir', '/dev/shm']
Changed DISPLAY to: :1
Starting emulator with comand: ['vglrun', 'mupen64plus', '--resolution', '640x480', '--input', '/usr/local/lib/mupen64plus/mupen64plus-input-bot.so', '/home/marty/Development/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64']
Traceback (most recent call last):
  File "play.py", line 67, in <module>
    env = gym.make('Mario-Kart-Luigi-Raceway-v0')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/marty/Development/gym-mupen64plus/gym_mupen64plus/envs/MarioKart64/mario_kart_env.py", line 32, in __init__
    super(MarioKartEnv, self).__init__(mk_config['ROM_NAME'])
  File "/home/marty/Development/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 64, in __init__
    self.xvfb_process, self.emulator_process = self._start_emulator(rom_name=rom_name)
  File "/home/marty/Development/gym-mupen64plus/gym_mupen64plus/envs/mupen64plus_env.py", line 226, in _start_emulator
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Close called!
```

**Comment by kevinhughes27** [comment]
looks more like the gym at a quick glance. Its fine to have the issue here though since the projects are super related at this point

**Comment by bzier** [comment]
Yeah, I believe that is related to the gym environment. The same issue came up over the weekend. I believe you need to install `vglrun` and I probably need to make that more clear in the readme. Check out the issue here for more problems and potential solutions (we're still working through it): https://github.com/bzier/gym-mupen64plus/issues/12

**Comment by millerda** [comment]
After installing VirtualGL, I do get farther in the process when trying to run. Eventually I get what I think must be output from the model/environment `('Frame ', '10', ': ', '[0, 0, 1, 0, 0]')`. After what seems like a few minutes, I get another line `('Frame ', '80', ': ', '[0, 0, 1, 0, 0]')`. My model isn't doing very well right now, so it isn't unexpected that these are the same (still working through controller issues mentioned above).

When I try running without Xvfb, I do not get a mupen64plus window opening, however I do still get the same output ('Frame ', '10', ': ', '[0, 0, 1, 0, 0]')`. I do see some concerning output related to mupen64plus however:

```
Core Warning: No video plugin attached.  There will be no video output.
Core Warning: No RSP plugin attached.  The video output will be corrupted.
```

If I copy and run the mupen64plus command just as it is specified (i.e. `['mupen64plus', '--resolution', '640x480', '--input', '/usr/local/lib/mupen64plus/mupen64plus-input-bot.so', '/home/marty/Development/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64']` I get the same "Core Warning"s, so there may be some issue with differing (or nonexistent as in my case) default video plugins. Maybe adding these in the config.yml file and explicitly incorporating those into the run command would clear this up? I will try it out and post back

**Comment by millerda** [comment]
I think this can be closed because installing VirtualGL fixed the initial issue I had. I have also opened a new issue on the gym-mupen64plus project relating to my last comment here, fits better there.

Feel free to reopen as necessary
