### ISSUE TITLE
Problem with installing wxPython==4.0.0a1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by MarBol95** [kevinhughes27/TensorKart#41]
I'm using Ubuntu 14.04 and while installing the requirements, it stopped because wxPython version 4.0.0a1 couldn't be installed. But without this recent version, record.py won't work. I guess it doesn't know img = wx.Image(320,240). It says: TypeError: String or Unicode type required. Is there any quick solution or workaround?

**Comment by kevinhughes27** [comment]
We only recently updated to the latest wx version, you should be able to see the changes in the recent commits. Old versions should work fine but they seem to have changed the API around a bit, I seem to recall it used to be wx.Bitmap. I'm on vacation or else I'd dig in a bit more.

**Comment by kevinhughes27** [comment]
Hmm the changes aren't in the recent source. Why won't the latest wx install?

**Comment by sirvincent** [comment]
Hey, MarBol95 what solved this problem for me was installing the dependencies needed for wxPython, after installing just use pip install wxPython.

see: https://github.com/wxWidgets/Phoenix

The two commands I used to get wxPython up and running: 
sudo apt-get install dpkg-dev build-essential libwebkitgtk-dev libjpeg-dev libtiff-dev libgtk2.0-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev

pip install wxPython

Hopefully this also works for you :)
