### ISSUE TITLE
Aspect ratio of processed images not equal to raw images

### ISSUE THREAD

**Issue by crypdick** [kevinhughes27/TensorKart#42]
I noticed that the [Sample class](https://github.com/kevinhughes27/TensorKart/blob/master/utils.py#L36-L37) has shape (200, 66, 3) while the raw images have an aspect of (640, 480, 3). Why is there a difference in aspect ratio?

**Comment by kevinhughes27** [comment]
The first image is the default emulator window size. The second is what Nvidia used in their research paper. I used their model and I didn't want to change the network size to make things easier. That is why you see a difference.

It shouldn't make a difference as the data is all still there albeit resized or skewed a bit. It should be possible to change the network to work on the same aspect ratio it just involves a bit of math. Should be easier as well now that we're using Keras.

**Comment by crypdick** [comment]
Makes sense. Is that why the output layer has 10 units when there are only ~5 controls?

**Comment by kevinhughes27** [comment]
Nah thats because originally I was going to use more of the controller than I ended up using.
