### ISSUE TITLE
can't drive, no direction event

### ISSUE THREAD

**Issue by zhangchunsheng** [kevinhughes27/TensorKart#43]
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4

**Comment by kevinhughes27** [comment]
This sounds like an issue with the emulator not working for you. Can you post some more details, OS and mupen64plus version. Also what kind of joystick are you using?

**Comment by zhangchunsheng** [comment]
macOS 10.12.6
mupen64plus-bundle-osx64-2.5

I'm not sure about which joystick I'm using. -1 means no joystick. I think it's auto.
# Specifies which joystick is bound to this controller: -1=No joystick, 0 or more= SDL Joystick n    umber
device = -1

**Comment by kevinhughes27** [comment]
You need a controller plugged into your computer. I use an xbox 360 controller. The code could work with the keyboard but would require a fair amount of changes

**Comment by zhangchunsheng** [comment]
Alright, thanks.
