### ISSUE TITLE
Screenshots Black Screen on Ubuntu 14

### ISSUE THREAD

**Issue by xaviervasques** [kevinhughes27/TensorKart#45]
Hello,
What would be the reasons to have black screenshots when using record.py ?
Thanks,
Xavier

**Comment by kevinhughes27** [comment]
No idea. Could be related to #15. We use `wx Python` to take the screenshots currently so the issue is really with that library. Figuring out exactly what is going on could be tough I'd recommend a newer version of Ubuntu instead if you can.

**Comment by xaviervasques** [comment]
Hi Kevin and thanks for your reply. I will try with ubuntu 16. What Linux distribution did you use for TensorKart ?

**Comment by kevinhughes27** [comment]
I used Linux Mint 18

**Comment by xaviervasques** [comment]
Thanks Kevin. It works now. The reason was the 3D acceleration option enabled in virtualbox ...

**Comment by kevinhughes27** [comment]
Glad you figured it out! Would you mind PRing that information to the Readme somewhere? Maybe a troubleshooting section.

Thanks!
