### ISSUE TITLE
Agent Output

### ISSUE THREAD

**Issue by simama** [kevinhughes27/TensorKart#49]
I guess this is not a technical issue, but maybe it is, who knows :smile: So after training the agent on 10 races, and then running through play.py, my agent outputs only accelerate command ([0 0 1 0 0]). Manual override works well. Data CSVs have all inputs recorded properly, and all images are from the game. I train for 200 epochs ( around 8k data samples) and loss goes down to around 0.3, while eval loss hovers around 0.5. Btw, you should track eval accuracy, not loss, it would be more informative.

Does it look like a technical error, or just bad agent? During the data recording, accelerate command is always constant (1), so maybe it just learned to output that all the time...

**Comment by kevinhughes27** [comment]
Did you read the blog post about aliasing? That's the hardest part about training. I drove pretty slow and careful to get it working initially.

**Comment by simama** [comment]
Damn, I missed that :D In the meantime, I switched the net to train and output just steering angles. In that way I did get some steering outputs, but it was bad. I'll re-record the data with slow driving. And maybe also try RL afterwards.

**Comment by kevinhughes27** [comment]
Let me know how it goes!
