### ISSUE TITLE
module wx not found.

### ISSUE THREAD

**Issue by TH4NOS** [kevinhughes27/TensorKart#52]
![screenshot_20170921_140636](https://user-images.githubusercontent.com/29422822/30686523-25d0a628-9ed6-11e7-82bc-44ec3ab8f8d9.png)

**Comment by bzier** [comment]
Hey @TH4NOS , see the discussion on issue #41 
The package `wx` has been replaced with `wxPython`

**Comment by TH4NOS** [comment]
@bzier Thanks for the reply. I will try replacing the requirements.
