### ISSUE TITLE
Use PIL to take screenshots instead of wx

### ISSUE THREAD

**Issue by mBeierl** [kevinhughes27/TensorKart#8]
Skip to bottom for final suggestion:

While looking through your project and trying it out myself, I had problems running it on Windows.

The error was as follows
`Traceback (most recent call last):
  File "A:/github/mBeierl/TensorKart/record.py", line 207, in <module>
    app.frame = MainWindow()
  File "A:/github/mBeierl/TensorKart/record.py", line 30, in __init__
    self.create_main_panel()
  File "A:/github/mBeierl/TensorKart/record.py", line 49, in create_main_panel
    img = wx.Image(320,240)
  File "A:\Programme\Anaconda2\lib\site-packages\wx-3.0-msw\wx\_core.py", line 2882, in __init__
    _core_.Image_swiginit(self,_core_.new_Image(*args, **kwargs))
TypeError: String or Unicode type required`

I guess it may be because I don't have wx version 3.0.3. the only version available for windows seems to be 3.0.
First: Is that correct or is there a 3.0.3 version out there that I missed?

Second: I then started to fix those small issues
e.g. in record.py line 49
```
img = wx.Image(320,240) 
 self.image_widget = wx.StaticBitmap(self.img_panel, wx.ID_ANY, wx.Bitmap(img))
```
to
```
img = wx.EmptyBitmap(320,240) 
self.image_widget = wx.StaticBitmap(self.img_panel, wx.ID_ANY, img)
```

Then it worked without errors, but only black screenshots were created.

Finally, I tried PIL (http://effbot.org/imagingbook/) and was able to create a working screenshot with

```
import psyscreenshot as ImageGrab
im = ImageGrab.grab(bbox=(2,52,320,290) # worked best with emulator window x1
im.save("test.png")
```

Do you think it would be worth the effort to change the screenshot system to use this library instead? I have no idea how good the performance is with this library. Will test this out and update this issue with my progress.

Cheers and thanks for this great project!

**Comment by kevinhughes27** [comment]
Yes please post back your findings! Open a PR if you can so I can check try it out easily. I seem to recall looking at this library and having it not work on my machine. 

In general I would like to move away from depending on `wx`. This was a choice I made a few years ago when I built the record tool and I feel like there might be simpler solutions.

**Comment by mBeierl** [comment]
OK, so PIL doesn't work cross-platform. So that is a no go.

I fixed the issue with the black screenshots I was having by modifying the code in record.py. I will do a PR with my changes.

**Comment by kevinhughes27** [comment]
That's too bad!
