### ISSUE TITLE
record.py dont recive joystick signal.

### ISSUE THREAD

**Issue by dammianhr** [kevinhughes27/TensorKart#9]
i install all dependencies, test the joystick and work fine but when i test record.py, it dont get the joystick signals.

pd: dont create screenshots in record mode.
SO: ubuntu 16.04

**Comment by kevinhughes27** [comment]
Does the graph respond to your input before pressing record? Its likely that pygame isn't connecting to your joystick even if you can play the emulator.

**Comment by millerda** [comment]
Another option might be that your joystick buttons are numbered differently. I had this issue with a generic gamepad I had lying around and I needed to adjust which buttons were polled in the XboxController class. You can use jstest-gtk to see what the numbers for your controller's buttons are (also important that these match what is in your mupen64plus config file).
